### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by lubieapki** [beltex/dshb#32]
Hi, There will be a version for iOS?

**Comment by beltex** [comment]
Hello @lubieapki!

Could you expand on what your use case would be? I'm assuming you mean for use on a jailbroken device, correct? It is not something I have considered. However, if there is enough demand for it, we _could_ explore it. I’m not familiar enough with jailbreaking to speak to how useful it would be in that context (I know that `top(1)` is already available of course **[1]**), though my sense is that it would be a narrow use case.

There is an open issue in SystemKit (the main stat library for dshb), https://github.com/beltex/SystemKit/issues/9, which would cover mostly everything that would be needed for iOS, though that was opened in the context of SystemKit as just a standalone library.

**[1]** _Mac OS X and iOS Internals: To the Apple's Core_, page 179
