### ISSUE TITLE
Update to Swift 2.3 or 3

### ISSUE THREAD

**Issue by zmwangx** [beltex/dshb#36]
Hi, Homebrew maintainer here.

El Capitan and Sierra folks are on Xcode 8 (with Swift 3 or 2.3) already so `dshb` no longer builds:

```
==> make release
xcodebuild -configuration Release build
=== BUILD TARGET dshb OF PROJECT dshb WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **


The following build commands failed:
    Check dependencies
(1 failure)
make: *** [build] Error 65
```

Could you please update to Swift 2.3 or 3 and cut a new release? Otherwise we'll have to move the formula to boneyard. Thanks.

**Comment by beltex** [comment]
Hello @zmwangx!

Thanks for the heads up, much appreciated! Will do ASAP! Is there a deadline for this?

**Comment by yorch** [comment]
While a new release is finished, is there a way to build it on Sierra (XCode 8) or not at all?
Thanks!

**Comment by zmwangx** [comment]
@beltex Sorry, I must have missed your comment.

There's no hard deadline because we're still in the process of dealing with a good number of packages that don't work on Sierra, one by one, meaning that we're still doing what we could. But once we've exhausted work we could do on our side (maybe in a week or two, maybe in a month or two) we'll have to axe the remaining ones.

May I ask if you plan to add Swift 3/2.3 support, or is this a lost cause?

**Comment by alexpovh** [comment]
I hope this helps https://github.com/beltex/dshb/pull/37

**Comment by JMY1000** [comment]
SMCKit is supposedly updated to Swift 3 now, but [it doesn't build properly either.](https://github.com/beltex/SMCKit/issues/30) 🤷 ¯\_(ツ)_/¯

**Comment by ilovezfs** [comment]
@beltex any updates here?

**Comment by JMY1000** [comment]
@ilovezfs Not that I know of :/

**Comment by beltex** [comment]
Done! Thanks to all for the help, and once again, sorry about the super late response. Will cut a new release shortly.

**Comment by ilovezfs** [comment]
Thanks @beltex! :bowing_man:
