### ISSUE TITLE
Add support for disk usage statistics

### ISSUE THREAD

**Issue by MichelDiz** [beltex/dshb#39]
Hi there!

So, is very strange for me coming from Windows environment deal with no info about transferring time or speeds. At Windows We have the indicator like "90MB/s" but in Mac Os is totaly blindness. oO

I tryout use some "free apps" but none of then really do what Windows does. And one called "Speed" (blue icon) do some trick with bash commands but with large files stay "quiet". He does Zipping before transfering. And Makes me nervous.

I wanted something like the "Task manager". Who says the use of the HDD/SDD, says about IO use, speeds and so on. But there's nothing close to this on AppStore.

So, there is. Best Regards.

**Comment by beltex** [comment]
Hello @MichelDiz!

Sorry about the late response!

I believe your asking for disk (and network?) usage statistics, correct?

The macOS equivalent of Window's Task Manager is Apple's [Activity Monitor](https://support.apple.com/en-us/HT201464) (included with the OS), which includes disk usage stats (also network usage). Here's a screenshot from Apple's docs:

<img width="600" alt="yosemite-activity_monitor-disk" src="https://user-images.githubusercontent.com/2666961/29044660-7438beba-7b8e-11e7-9691-6db72e86245a.png">

Would love to add support for such stats, no timeline on them though at the moment.

**Comment by MichelDiz** [comment]
Thank you for respond. I'm using iStats now. I'm already getting used to the MAC OS environment.
