### ISSUE TITLE
Does not compile on macOS 10.12 or 10.13

### ISSUE THREAD

**Issue by ilovezfs** [beltex/dshb#40]
@beltex We're having to resort to hacks in Homebrew to continue to keep the `dshb` formula. Some of the other maintainers would simply like to remove it at this point. See https://github.com/Homebrew/homebrew-core/pull/17493. Any chance we could get https://github.com/beltex/dshb/pull/37 merged soon?

**Comment by ilovezfs** [comment]
Also doesn't compile on 10.11 with the current Xcode (8.2.1).

**Comment by beltex** [comment]
Hello @ilovezfs!

So sorry about the super late response on this! Works been hectic this past year :) Taking a look at this now, hope to have an update for you soon.

**Comment by ilovezfs** [comment]
@beltex thanks for the reply! :heart:

**Comment by beltex** [comment]
@ilovezfs: Done! Should compile on both Xcode 8 & 9 now (Swift 3.1 & 3.2). Release has been cut as well (`0.2.0`). Let me know if you have any other issues. I'll comment on that Homebrew ticket as well.

Thanks for reaching out!

**Comment by ilovezfs** [comment]
@beltex you're welcome, and thanks for the new release! Voilà: https://github.com/Homebrew/homebrew-core/pull/19006.

**Comment by beltex** [comment]
@ilovezfs: Wow that was fast, awesome! 😄 np!

**Comment by ilovezfs** [comment]
@beltex 0.2.0 has now shipped in Homebrew!

https://github.com/Homebrew/homebrew-core/commit/ac754597df9eff2c4c3fe5265522ee4a5fe48595
https://github.com/Homebrew/homebrew-core/commit/d46413a167143208b5187c03f7ec1fd5ef91d063

**Comment by beltex** [comment]
🎉
